protected/controllers/LifegroupController.php
<?php

class LifegroupController extends Controller
{

	public function actionIndex()
	{
		$this->layout='//layouts/column1';

		$konten = Life::model()->getAllDataByDate($_GET['writer'], $month,$year, false, false, $this->languageID);

		$this->pageTitle = 'Life Group - ' . $this->pageTitle;

		$this->render('index', array(
			// 'menu'=>$listMenu,
			// 'writer'=>$writer,
			'data'=> $konten,
			// 'subMenu'=>$subMenu,
		));
	}
	public function actionDetail($id)
	{
		$this->layout='//layouts/column1';

		$detail = Life::model()->getData($id, $this->languageID);
		
		$konten = Life::model()->getAllDataByDate($_GET['writer'], $month,$year, false, false, $this->languageID);

		// $dataSub = Blog::model()->getAllData(5, false, $this->languageID);

		// $dataFooter = Blog::model()->getAllData(3, $id, $this->languageID);

		$this->pageTitle = $detail->title . ' - Life Group - ' . $this->pageTitle;
		$this->render('detail', array(
			'detail' => $detail,
			'data'=>$konten,
			// 'dataSub' => $dataSub,
			// 'dataFooter' => $dataFooter,
		));
	}

	public function actionDetailinstagram($id)
	{
		$this->layout='//layouts/column1';

		$detail = Life::model()->getData($id, $this->languageID);
		
		$konten = Life::model()->getAllDataByDate($_GET['writer'], $month,$year, false, false, $this->languageID);

		// $dataSub = Blog::model()->getAllData(5, false, $this->languageID);

		// $dataFooter = Blog::model()->getAllData(3, $id, $this->languageID);

		$this->pageTitle = $detail->title . ' INSTAGRAM - Life Group - ' . $this->pageTitle;
		$this->render('instagram', array(
			'detail' => $detail,
			'data' => $konten,
			// 'dataSub' => $dataSub,
			// 'dataFooter' => $dataFooter,
		));
	}
}

protected/views/lifegroup/detail.php
<div class="outer-content">
			
			<div class="clear"></div>
			<div class="outer-inside-content">
				<div class="prelatif container">
						<div class="clear height-50"></div>
						<div class="clear visible-lg height-45"></div>
						<div class="top">
							<div class="left title-topsitel"><b>Life Group</b> at New Life Church</div>
							<div class="right breadcumb text-raleway margin-right-25">
								<a href="<?php echo CHtml::normalizeUrl(array('home/index')); ?>">Home</a>  &gt;  <a href="<?php echo CHtml::normalizeUrl(array('lifegroup/index')); ?>">Life Group</a> &gt; <?php echo $detail->title ?>
							</div>
							<div class="clear"></div>
						</div>
						<div class="clear height-10"></div>
						<div class="height-2"></div>
						<div class="lines-black"></div>
						<div class="clear height-35"></div>
						
						<div class="inside content-text">
							<div class="row">
								<div class="col-md-3">
									<div class="left-content">
										<div class="left b-previousdblog">
											<a href="<?php echo CHtml::normalizeUrl(array('lifegroup/index')); ?>" class="bt previous-blog" style="width: 80px;">&lt; Back</a>
										</div>
										<div class="clear height-20"></div>
											<h6 class="title-newsst">IN THIS GROUP</h6>
											<div class="clear height-5"></div>
											<div class="list-sect-blogs">
												<ul>
													<li class="active"><a href="<?php echo CHtml::normalizeUrl(array('lifegroup/detail', 'id'=> $_GET['id'], 'slug'=>Slug::create($detail->title) ) ); ?>">OVERVIEW</a></li>
													<li><a href="<?php echo CHtml::normalizeUrl(array('lifegroup/detailinstagram', 'id'=> $_GET['id'], 'slug'=>Slug::create($detail->title) )); ?>">INSTAGRAM</a></li>
												</ul>
												<div class="clear"></div>
											</div>

											<div class="clear height-35"></div>
											<h6 class="title-newsst">LIFE GROUPS</h6>
											<div class="clear height-5"></div>
											<div class="list-sect-blogs">
												<ul>
													<?php foreach ($data as $key => $dta_All): ?>
													<li <?php echo ($dta_All->id == $_GET['id'])? 'class="active"': ''; ?> ><a href="<?php echo CHtml::normalizeUrl(array('lifegroup/detail', 'id'=> $dta_All->id, 'slug'=>Slug::create($dta_All->title) )); ?>"><?php echo $dta_All->title ?></a></li>
													<?php endforeach ?>
												</ul>
												<div class="clear"></div>
											</div>



										<div class="clear"></div>
									</div>
								</div>
								<div class="col-md-9">
									<div class="right-content right w755">
											
											<div class="data-news-blog">
													<div class="item no-border">
														<div class="top">
															<h1 class="titlt"><?php echo $detail->title ?></h1>
															<div class="clear height-15"></div>
														</div>
														<div class="clear height-15"></div>
														<div class="center">
															<div class="pic"><img class="img-responsive" src="<?php echo Yii::app()->baseUrl.ImageHelper::thumb(752,446, '/images/life/'.$detail->image , array('method' => 'adaptiveResize', 'quality' => '90')) ?>" alt="<?php echo Slug::create($detail->title); ?>" title="<?php echo Slug::create($detail->title); ?>" ></div>
																<div class="clear height-35"></div>
															<div class="desc">
																<?php echo $detail->content; ?>

																<div class="clear"></div>
															</div>
															<div class="clear height-25"></div>
														</div>

													</div>

												<div class="clear"></div>
											</div>

											<!-- <div class="clear height-40"></div> -->
											<div class="clear height-15"></div>
											
											<!-- <div class="b-othersblog-data">
												<div class="top">
													<div class="dtitle">Other Blogs</div>
												<div class="clear height-10"></div>
												</div>
												<div class="clear"></div>
												<div class="middle">
														<div class="clear height-20"></div>
														<div class="list">
															<div class="row">
																<div class="col-md-6">
																	<div class="item">
																		<div class="pic margin-right-10 left">
																			<img src="<?php echo Yii::app()->baseUrl; ?>/asset/images/thumb-news-pic2.jpg" alt="">
																		</div>
																		<div class="left text w265">
																			<p>&quot;Breathtaking&quot;: The White House Releases Its Climate Heavy Hitter on the Polar Vortex</p>
																			<div class="clear height-2"></div>
																			<span class="date">January 15, 2014</span>
																			<div class="clear height-2"></div>
																			<span class="ps">Ps. Irwan Alexander</span>
																		</div>
																		<div class="clear"></div>
																	</div>
																</div>
																<div class="col-md-6">
																	<div class="item">
																		<div class="pic margin-right-10 left">
																			<img src="<?php echo Yii::app()->baseUrl; ?>/asset/images/thumb-news-pic2.jpg" alt="">
																		</div>
																		<div class="left text w265">
																			<p>&quot;Breathtaking&quot;: The White House Releases Its Climate Heavy Hitter on the Polar Vortex</p>
																			<div class="clear height-2"></div>
																			<span class="date">January 15, 2014</span>
																			<div class="clear height-2"></div>
																			<span class="ps">Ps. Irwan Alexander</span>
																		</div>
																		<div class="clear"></div>
																	</div>
																</div>
															</div>
															<div class="clear"></div>
														</div>
													<div class="clear"></div>
												</div>
												<div class="clear"></div>
											</div> -->
											

										<div class="clear"></div>
									</div>
								</div>
							</div>
							<div class="clear height-50"></div>
							<div class="clear height-15"></div>

							<div class="clear"></div>
						</div>

					<div class="clear"></div>
				</div>
				<div class="clear"></div>
			</div>
			

	<div class="clear"></div>
</div>

protected/views/lifegroup/index.php
<style type="text/css">
	.t-back-fc-healing {
		margin-top: 125px;
	}
</style>
<div class="outer-content">
			<div class="ill-inside-pages-outer3" style="background-image: url(<?php echo Yii::app()->baseUrl; ?>/asset/images/ill-life-group-menu.jpg);">
				<!-- <img class="img-responsive" src="<?php // echo Yii::app()->baseUrl; ?>/asset/images/ill-about.jpg" alt=""> -->
					<div class="ds-tx-illinside">
							<div class="prelatif container">
								<div class="clear height-50"></div>
								<div class="height-20"></div>
								<div class="t-back-fc-healing center">
									We dream of creating environments where people from every walk of life can connect deeply with God and with others who are heading in the same direction. For a growing church like New Life Church the only way to do that is to grow smaller as we grow larger.
								</div>
							</div>
					</div>
			</div>
			<div class="clear"></div>
			<div class="lines-pink"></div>

			<div class="outer-inside-content">
				<div class="prelatif container">
						<div class="clear height-35"></div>
						<div class="top">
							<div class="left title-topsitel"><b>Life Group</b> at New Life Church</div>
							<div class="right breadcumb text-raleway">
								<a href="<?php echo CHtml::normalizeUrl(array('home/index')); ?>">Home</a>  &gt;  <b>Life Group</b>
							</div>
							<div class="clear"></div>
						</div>
						<div class="clear height-10"></div>
						<div class="height-2"></div>
						<div class="lines-black"></div>
						<div class="clear height-35"></div>
						
						<div class="inside content-text">

							<div class="list-data-healing">
								<div class="row">
									<?php foreach ($data as $key => $v_lfgroup): ?>
									<div class="col-md-4">
										<div class="item">
											<div class="pic">
												<a href="<?php echo CHtml::normalizeUrl(array('lifegroup/detail', 'id'=> $v_lfgroup->id, 'slug'=>Slug::create($v_lfgroup->title) )); ?>">
													<img class="img-responsive" src="<?php echo Yii::app()->baseUrl.ImageHelper::thumb(349,198, '/images/life/'.$v_lfgroup->image , array('method' => 'adaptiveResize', 'quality' => '90')) ?>" alt="<?php echo Slug::create($v_lfgroup->title); ?>" title="<?php echo Slug::create($v_lfgroup->title); ?>">
												</a>
											</div>
											<div class="clear height-10"></div>
											<div class="name"><a href="<?php echo CHtml::normalizeUrl(array('lifegroup/detail', 'id'=>$v_lfgroup->id, 'slug'=>Slug::create($v_lfgroup->title) )); ?>"><?php echo $v_lfgroup->title ?></a></div>
											<div class="clearfix"></div>
										</div>
										<div class="clear height-30"></div>
									</div>
									<?php endforeach; ?>
									<div class="clearfix"></div>
								</div>
							</div>

							<div class="clear height-20"></div>
							<div class="clear height-15"></div>

							<div class="clear"></div>
						</div>

					<div class="clear"></div>
				</div>
				<div class="clear"></div>
			</div>
			

	<div class="clear"></div>
</div>

protected/views/lifegroup/instagram.php
<div class="outer-content">
			<div class="clear"></div>
			<div class="outer-inside-content">
				<div class="prelatif container">
						<div class="clear height-50"></div>
						<div class="clear visible-lg height-45"></div>
						<div class="top">
							<div class="left title-topsitel"><b>Life Group</b> at New Life Church</div>
							<div class="right breadcumb text-raleway margin-right-25">
								<a href="<?php echo CHtml::normalizeUrl(array('home/index')); ?>">Home</a>  &gt;  <a href="<?php echo CHtml::normalizeUrl(array('lifegroup/index')); ?>">Life Group</a> &gt; <?php echo $detail->title ?>
							</div>
							<div class="clear"></div>
						</div>
						<div class="clear height-10"></div>
						<div class="height-2"></div>
						<div class="lines-black"></div>
						<div class="clear height-35"></div>
						
						<div class="inside content-text">
							<div class="row">
								<div class="col-md-3">
									<div class="left-content">
										<div class="left b-previousdblog">
											<a href="<?php echo CHtml::normalizeUrl(array('lifegroup/index')); ?>" class="bt previous-blog" style="width: 80px;">&lt; Back</a>
										</div>
										<div class="clear height-20"></div>
											<h6 class="title-newsst">IN THIS GROUP</h6>
											<div class="clear height-5"></div>
											<div class="list-sect-blogs">
												<ul>
													<li><a href="<?php echo CHtml::normalizeUrl(array('lifegroup/detail', 'id'=> $_GET['id'], 'slug'=>Slug::create($detail->title) ) ); ?>">OVERVIEW</a></li>
													<li <?php echo ($this->action->id == 'detailinstagram')? 'class="active"': ''; ?>><a href="<?php echo CHtml::normalizeUrl(array('lifegroup/detailinstagram', 'id'=> $_GET['id'], 'slug'=>Slug::create($detail->title) )); ?>">INSTAGRAM</a></li>
												</ul>
												<div class="clear"></div>
											</div>

											<div class="clear height-35"></div>
											<h6 class="title-newsst">LIFE GROUPS</h6>
											<div class="clear height-5"></div>
											<div class="list-sect-blogs">
												<ul>
													<?php foreach ($data as $key => $dta_All): ?>
													<li <?php echo ($dta_All->id == $_GET['id'])? 'class="active"': ''; ?> ><a href="<?php echo CHtml::normalizeUrl(array('lifegroup/detail', 'id'=> $dta_All->id, 'slug'=>Slug::create($dta_All->title) )); ?>"><?php echo $dta_All->title ?></a></li>
													<?php endforeach ?>
												</ul>
												<div class="clear"></div>
											</div>



										<div class="clear"></div>
									</div>
								</div>
								<div class="col-md-9">
									<div class="right-content right w755">
											
											<div class="data-news-blog">
													<div class="item no-border">
														<div class="top">
															<h1 class="titlt"><?php echo $detail->title ?> INSTAGRAM</h1>
															<div class="clear height-15"></div>
														</div>
														<div class="clear height-15"></div>
														<div class="center">
															<?php if ($detail->instagram != ''): ?>
															<div id="data-instagram" class="list-instagram-lifegroup">
																
																<div class="clearfix"></div>
															</div>
															<?php else: ?>
															<p class="text-left">There are no content at the moment</p>
															<?php endif ?>
															

															<div class="clear height-25"></div>
														</div>

														<div id="instafeed" class="hidden"></div>
														<div class="clear"></div>
													</div>

												<div class="clear"></div>
											</div>

											<!-- <div class="clear height-40"></div> -->
											<div class="clear height-15"></div>
											
										<div class="clear"></div>
									</div>
								</div>
							</div>
							<div class="clear height-50"></div>
							<div class="clear height-15"></div>

							<div class="clear"></div>
						</div>

					<div class="clear"></div>
				</div>
				<div class="clear"></div>
			</div>

	<div class="clear"></div>
</div>
<!-- Instafeed -->
<?php if ($detail->instagram != ''): ?>
<script type="text/javascript" src="<?php echo Yii::app()->baseUrl; ?>/asset/js/instafeed.min.js"></script>
<script type="text/javascript">
    var feed = new Instafeed({
        get: 'tagged',
        tagName: '<?php echo $detail->instagram ?>',
        clientId: '3c03a0fd2a354ad59621aea34ceeb3be',
        // resolution : 'thumbnail',
        template: '<div class="item"><a href="{{link}}"><img class="img-responsive" src="{{image}}" /></a><br>  <div class="instagram_image_meta"><div class="likes instagram_image_meta_item"> <p><a class="icon-heart" href="{{link}}" target="_blank" title="{{caption}}" ><i class="icon-instalikes"></i> {{likes}}</a></p></div>          <div class="comments instagram_image_meta_item"> <p><a class="icon-bubble" href="{{link}}" target="_blank" title="{{caption}}" ><i class="icon-instacomment"></i> {{comments}}</a></p> </div> </div> </div>',
        after: function(){
             // $("#instafeed").owlCarousel();
             var isidataGal =  $('#instafeed').html();
             $("#data-instagram").html(isidataGal);
            },
    });

    feed.run();
</script>
<style type="text/css">
	#data-instagram{
		/*width: 100%;*/
		margin-right: -15px;
	}
	#data-instagram > .item{
		width: 143px;
		float: left;
		margin-bottom: 18px;
		margin-right: 9px;
		background-color: #FFF;
	}
	.list-instagram-lifegroup div .instagram_image_meta, 
	.wrap-owlgallery .owl-carousel div .instagram_image_meta, 
	#instafeed .instagram_image_meta{
		margin-top: -10px;
		vertical-align: middle;
		line-height: 29px;
		display: block;
	}
	.list-instagram-lifegroup div .instagram_image_meta .instagram_image_meta_item, 
	.wrap-owlgallery .owl-carousel div .instagram_image_meta .instagram_image_meta_item, 
	#instafeed .instagram_image_meta .instagram_image_meta_item{
		width: 30%;
		padding-bottom: 6px;
	}
</style>
<?php endif ?>